service: dolphin-server

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stages:
    - prod
    - dev
  NODE_ENV:
    prod: production
    dev: development

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  environment:
    NODE_ENV: ${self:custom.NODE_ENV.${self:provider.stage}}
    TZ: Asia/Seoul

functions:
  dolphin:
    handler: src/handler.dolphin
    events:
      - http:
          path: calendar
          method: get
      - http:
          path: notices
          method: get
      - http:
          path: dayshuttle
          method: get
      - http:
          path: allshuttle
          method: get
      - http:
          path: nextshuttle
          method: get
      - http:
          path: allnode
          method: get
      - http:
          path: specificnode/{bstopid}
          method: get
      - http:
          path: depart190
          method: get
      
