# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: dolphin-server

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stages:
    - prod
    - dev
  NODE_ENV:
    prod: production
    dev: development

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  environment:
    NODE_ENV: ${self:custom.NODE_ENV.${self:provider.stage}}
    TZ: Asia/Seoul

functions:
  dolphin:
    handler: src/handler.dolphin
    events:
      - http:
          path: calendar
          method: get
      - http:
          path: notices
          method: get
      
