name: Serverless Deploy

# Triggers the action everty time there is a code push to the master branch
on:
  workflow_dispatch:

# Specify what jobs to run
jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-latest
    env: #Setup environmental variables for serverless deployment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: npm install dependencies
        run: npm install
      - name: Serverless
        uses: serverless/github-action@master
        with:
          args: name: Serverless Deploy

# Triggers the action everty time there is a code push to the master branch
on:
  push:
    branches:
      - master

# Specify what jobs to run
jobs:
  deploy-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    env: #Setup environmental variables for serverless deployment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: npm install dependencies
        run: npm install
      - name: Serverless
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
